# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVd_mRbdZ6QeiKKxU9Ps83FjM4I6SVQt
"""

import numpy as np
import pandas as pd
from sklearn import tree

dataset = pd.read_csv('PlayTennis.csv')

dataset["Wind"] = pd.factorize(dataset.Wind)[0]

dataset = dataset.drop(labels="PlayTennis", axis=1)
dataset = dataset.drop(labels="Outlook", axis=1)
dataset = dataset.drop(labels="Temperature", axis=1)
dataset = dataset.drop(labels="Humidity", axis=1)

dataset = dataset.to_numpy()

dataTraining = np.concatenate((dataset[0:111, :], dataset[139:250, :]), axis=0)
dataTesting = np.concatenate((dataset[111:139, :], dataset[250:278, :]), axis=0)

inputTraining = dataTraining[:, 0:6]
inputTesting = dataTesting[:, 0:6]
labelTraining = dataTraining[:, -1]
labelTesting = dataTesting[:, -1]

model = tree.DecisionTreeClassifier()

model = model.fit(inputTraining, labelTraining)

hasilPrediksi = model.predict(inputTraining)
print("Label sebenarnya : ", labelTesting)
print("Hasil prediksi   : ", hasilPrediksi)

prediksiBenar = (hasilPrediksi == labelTraining).sum()
prediksiSalah = (hasilPrediksi != labelTraining).sum()
print("Prediksi Benar : ",prediksiBenar, "data")
print("Prediksi Salah : ",prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")